- name: Initial server setup
  hosts: servers
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Upgrade all packages
      apt:
        upgrade: dist

    - name: Install essential packages
      apt:
        name:
          - ufw
          - fail2ban
          - vim
          - curl
          - git
          - htop
        state: present

    - name: Install Java 21
      apt:
        name: openjdk-21-jdk
        state: present

    - name: Install ImageMagick and development libraries
      apt:
        name:
          - imagemagick
          - libmagickwand-dev
        state: present

    - name: Set timezone to Los Angeles
      timezone:
        name: America/Los_Angeles

    - name: Verify Java installation
      command: java -version
      register: java_version
      changed_when: false

    - name: Display Java version
      debug:
        var: java_version.stderr

    - name: Verify ImageMagick installation
      command: convert -version
      register: imagemagick_version
      changed_when: false

    - name: Display ImageMagick version
      debug:
        var: imagemagick_version.stdout