spring:
  application:
    name: headblog
  datasource:
    url: jdbc:postgresql://localhost:5432/headblog
    username: headblog
    password: headblog
    driver-class-name: org.postgresql.Driver
    hikari:
      auto-commit: false
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000
      max-lifetime: 1200000
  jackson:
    property-naming-strategy: LOWER_CAMEL_CASE

jwt:
  # openssl rand -base64 32
  secret: "IJnor7miOnPl/MxO9uDZQQXkt8BfFrgenVeyLK7SFEQ="
  expiration: 1800000 # 30 minutes
  refresh-expiration: 3600000 # 60 minutes

logging:
  level:
    com.headblog.backend: INFO
    org.flywaydb: INFO
    org.jooq: WARN

server:
  port: 8080

cookie:
  secure: ${COOKIE_SECURE:false} # HTTP プロトコルを許可
  domain: ${COOKIE_DOMAIN:localhost} # ローカル用ドメイン
  same-site: ${COOKIE_SAME_SITE:Lax} # クロスオリジンのリスクを減らす
  http-only: ${COOKIE_HTTP_ONLY:true} # JavaScript からのアクセスを禁止

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000}
