spring:
  application:
    name: headblog
  datasource:
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DB:headblog}
    username: ${POSTGRES_USER:headblog}
    password: ${POSTGRES_PASSWORD:headblog}
    driver-class-name: org.postgresql.Driver
    hikari:
      auto-commit: false
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000
      max-lifetime: 1200000
  jackson:
    property-naming-strategy: LOWER_CAMEL_CASE
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 11MB

jwt:
  # openssl rand -base64 32
  secret: "IJnor7miOnPl/MxO9uDZQQXkt8BfFrgenVeyLK7SFEQ="
  expiration: 1800000 # 30 minutes
  refresh-expiration: 3600000 # 60 minutes

logging:
  level:
    com.headblog.backend: debug
    org.flywaydb: INFO
    org.jooq: INFO

server:
  port: 8080

cookie:
  secure: ${COOKIE_SECURE:false} # HTTP プロトコルを許可
  domain: ${COOKIE_DOMAIN:localhost} # ローカル用ドメイン
  same-site: ${COOKIE_SAME_SITE:Lax} # クロスオリジンのリスクを減らす
  http-only: ${COOKIE_HTTP_ONLY:true} # JavaScript からのアクセスを禁止

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000,http://localhost:8080}

gemini:
  api:
    key: ${GEMINI_API_KEY}
    url: ${GEMINI_API_URL}

storage:
  cloudflare:
    r2:
      bucket-name: ${R2_BUCKET_NAME}
      access-key: ${R2_ACCESS_KEY}
      secret-key: ${R2_SECRET_KEY}
      endpoint: ${R2_ENDPOINT}
      public-endpoint: ${R2_PUBLIC_ENDPOINT}
  media:
    max-file-size: 20MB
    supported-types:
      - image/jpeg
      - image/png
      - image/gif
      - image/webp
      - image/heic
    sizes:
      thumbnail:
        width: 150
        height: 150
        quality: 55    # サムネイル用の低品質
      small:
        width: 640     # スマートフォン向け
        height: 640
        quality: 65    # モバイル表示用の高品質
      large:
        width: 800    # PC向け
        height: 800
        quality: 70    # 大画面表示用の高品質